name: ROS Industrial CI

permissions:
  checks: write
  pull-requests: write

on:
  push:
  pull_request:
    branches:
      main
      dev
  schedule:
    - cron: '04 23 * * *'

jobs:
  industrial_ci:
    strategy:
      matrix:
        distro:
          - humble
          - iron
    runs-on: ubuntu-latest
    env:
      basedir: /home/runner/work/ros2_ros_bt_py/ros2_ros_bt_py
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.distro }}
          BASEDIR: ${{ env.basedir }}/.build
          ROS_REPO: main
          AFTER_INSTALL_TARGET_DEPENDENCIES: "pip3 install coverage[toml]"
          ENABLE_COVERAGE_TESTING: "true"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ env.basedir }}/.build/target_ws/build/ros_bt_py/pytest.xml
            ${{ env.basedir }}/.build/target_ws/build/**/*xunit.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ${{ env.basedir }}/.build/target_ws/build/ros_bt_py/coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
