name: ROS Industrial CI

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main
  schedule:
    - cron: '04 23 * * *'

jobs:
  industrial_ci:
    strategy:
      matrix:
        distro:
          - humble
          - iron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.distro }}
          BASEDIR: ${{ github.workspace }}/.build
          ROS_REPO: main
          AFTER_INSTALL_TARGET_DEPENDENCIES: "pip3 install coverage[toml]"
          ENABLE_COVERAGE_TESTING: "true"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ github.workspace }}/.build/target_ws/build/**/*xunit.xml
            ${{ github.workspace }}/.build/target_ws/build/**/*pytest.xml
