name: ROS Industrial CI

permissions:
  checks: write
  pull-requests: write

on:
  push:
  pull_request:
    branches:
      main
      dev
  schedule:
    - cron: '04 23 * * *'

jobs:
  industrial_ci:
    env:
      ICI_BASEDIR: $GITHUB_WORKSPACE
    strategy:
      matrix:
        distro:
          - humble
          - iron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.distro }}
          BASEDIR: ${{ github.workspace }}/.build
          ROS_REPO: main
          AFTER_INSTALL_TARGET_DEPENDENCIES: "pip3 install coverage[toml]"
          ENABLE_COVERAGE_TESTING: "true"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            .build/target_ws/build/ros_bt_py/pytest.xml
            .build/target_ws/build/**/*xunit.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: .build/
          
